### ISSUE TITLE
Base table or view not found: 1146 Table 'c1test.customgrid_grid' doesn't exist

### ISSUE THREAD

**Issue by kai1083** [mage-eag/mage-enhanced-admin-grids#114]
Magento 1.9 /0.8.9

a:5:{i:0;s:96:"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'c1test.customgrid_grid' doesn't exist";i:1;s:3052:"#0 /var/www/clients/client1/web5/web/1.9/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/clients/client1/web5/web/1.9/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /var/www/clients/client1/web5/web/1.9/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /var/www/clients/client1/web5/web/1.9/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `main_ta...', Array)
#4 /var/www/clients/client1/web5/web/1.9/lib/Varien/Db/Adapter/Pdo/Mysql.php(428): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `main_ta...', Array)
#5 /var/www/clients/client1/web5/web/1.9/lib/Zend/Db/Adapter/Abstract.php(737): Varien_Db_Adapter_Pdo_Mysql->query('SELECT `main_ta...', Array)
#6 /var/www/clients/client1/web5/web/1.9/lib/Varien/Data/Collection/Db.php(734): Zend_Db_Adapter_Abstract->fetchAll('SELECT `main_ta...', Array)
#7 /var/www/clients/client1/web5/web/1.9/app/code/core/Mage/Core/Model/Resource/Db/Collection/Abstract.php(521): Varien_Data_Collection_Db->_fetchAll('SELECT `main_ta...', Array)
#8 /var/www/clients/client1/web5/web/1.9/lib/Varien/Data/Collection/Db.php(566): Mage_Core_Model_Resource_Db_Collection_Abstract->getData()
#9 /var/www/clients/client1/web5/web/1.9/app/code/community/BL/CustomGrid/Model/Observer.php(343): Varien_Data_Collection_Db->load()
#10 /var/www/clients/client1/web5/web/1.9/app/code/core/Mage/Core/Model/App.php(1338): BL_CustomGrid_Model_Observer->onControllerActionPreDispatch(Object(Varien_Event_Observer))
#11 /var/www/clients/client1/web5/web/1.9/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(BL_CustomGrid_Model_Observer), 'onControllerAct...', Object(Varien_Event_Observer))
#12 /var/www/clients/client1/web5/web/1.9/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('controller_acti...', Array)
#13 /var/www/clients/client1/web5/web/1.9/app/code/core/Mage/Core/Controller/Varien/Action.php(527): Mage::dispatchEvent('controller_acti...', Array)
#14 /var/www/clients/client1/web5/web/1.9/app/code/core/Mage/Adminhtml/Controller/Action.php(160): Mage_Core_Controller_Varien_Action->preDispatch()
#15 /var/www/clients/client1/web5/web/1.9/app/code/core/Mage/Core/Controller/Varien/Action.php(407): Mage_Adminhtml_Controller_Action->preDispatch()
#16 /var/www/clients/client1/web5/web/1.9/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('index')
#17 /var/www/clients/client1/web5/web/1.9/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#18 /var/www/clients/client1/web5/web/1.9/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#19 /var/www/clients/client1/web5/web/1.9/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#20 /var/www/clients/client1/web5/web/1.9/index.php(87): Mage::run('default', 'store')
#21 {main}";s:3:"url";s:38:"/admin/?SID=h5k9fq82c05f8er706ad9f5mq7";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}

**Comment by ikyandhi** [comment]
Thanks

**Comment by Jeeva-Rathinam** [comment]
What is mean "core_resource", could you please explain briefly.

**Comment by Jeeva-Rathinam** [comment]
I am newbie.. how can i check core_resource table, could you pls explain briefly?

**Comment by Jeeva-Rathinam** [comment]
How can i solve my error, a:5:{i:0;s:257:"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'MyDB.customgrid_grid' doesn't exist, query was: SELECT `main_table`.* FROM `customgrid_grid` AS `main_table` WHERE (`module_name` = 'admin') AND (`controller_name` = 'catalog_product')";i:1;s:2793:"#0 /home/abcd/public_html/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)

**Comment by seansan** [comment]
sorry I dont think you will get an answer here. Please use stackexchange or ask a DEV. See the error message: The table is not found. So probably it was not created. [Read more](https://www.google.nl/search?q=magento+%22Base+table+or+view+not+found%22&oq=magento+%22Base+table+or+view+not+found%22&aqs=chrome..69i57j0l5.3619j0j7&sourceid=chrome&ie=UTF-8)
