### ISSUE TITLE
js bug in categories admin panel with magento 1.9

### ISSUE THREAD

**Issue by telepath** [mage-eag/mage-enhanced-admin-grids#127]
When I open the categories in my backend, the category tabs are displayed for a second, then vanish, obviously because of some ajax error. Magento log shows no error, browser console shows this:

```
TypeError: blcg.Grid is undefined catalog_category:1512
TypeError: blcg.Grid is undefined catalog_category:1560
TypeError: blcg.Grid is undefined catalog_category:1567
ReferenceError: blcgConfigd38d882e91ed1fbe4a7d244570c65f3bCRSM is not defined catalog_category:1924
ReferenceError: blcgConfigd38d882e91ed1fbe4a7d244570c65f3bCRSM is not defined catalog_category:1996
ReferenceError: blcgConfigd38d882e91ed1fbe4a7d244570c65f3bCRSM is not defined catalog_category:2068
ReferenceError: blcgConfigd38d882e91ed1fbe4a7d244570c65f3bCRSM is not defined catalog_category:2140
ReferenceError: blcgConfigd38d882e91ed1fbe4a7d244570c65f3bCRSM is not defined catalog_category:2212
ReferenceError: blcgConfigd38d882e91ed1fbe4a7d244570c65f3bCRSM is not defined catalog_category:2284
ReferenceError: blcgConfigd38d882e91ed1fbe4a7d244570c65f3bCRSM is not defined catalog_category:2356
TypeError: blcg.Grid is undefined catalog_category:2521
TypeError: blcg.Grid is undefined catalog_category:3056
TypeError: blcg.Grid is undefined catalog_category:3062
TypeError: blcg.MessagesTabs is not a constructor catalog_category:3635
TypeError: blcg.Grid is undefined prototype.js line 612 > eval:3
```

Tested with 0.9.0 and 1.0.0-wip, same problem, removing eag stops the problem. I have no other extension that should interfere with categories.

How can I fix or further debug this?

**Comment by ErnstSchwechler** [comment]
sorry, but I still also have the console errors. I'm using 1.9.1.0 and the 0.9.0

TypeError: blcg.CustomColumn is undefined
TypeError: blcg.Grid.Export is not a constructor
TypeError: blcg.Renderer is undefined
TypeError: blcg.Renderer is undefined
TypeError: blcg.Renderer is undefined
TypeError: blcg.Renderer is undefined
TypeError: blcg.Renderer is undefined
TypeError: blcg.Grid.Config is not a constructor

What can I do to fix this?

Thanks for your help!

Regards,
Ernst

**Comment by mage-eag** [comment]
@ErnstSchwechler Can you check if the JS script of the extension is actually included on the admin pages (should be something like `js/bl/customgrid/config.js`) ?

**Comment by ErnstSchwechler** [comment]
thanks @mage-eag for your answer. maybe it was a caching problem cause today i logged in an locked at the article overview an the enhanched admin grid is working fine!
