### ISSUE TITLE
Errors installing from magentocommerce.com

### ISSUE THREAD

**Issue by charlievaughan-zz** [mage-eag/mage-enhanced-admin-grids#142]
I've tried installing versions 0.8.9, 0.8.4.4 and 0.8.4.3 from https://www.magentocommerce.com/magento-connect/enhanced-admin-grids-editor.html and I'm getting the following errors in the Magento Connect Manager, Magento 1.9.0.1:

<code>Checking dependencies of packages
Installing package community/BL_CustomGrid 0.8.9</code>

<code>CONNECT ERROR: Failed to open file /kunden/homepages/18/xxxxxxxxx/htdocs/magento/downloader/.cache/community/BL_CustomGrid-0.8.9/app/design/adminhtml/default/default/template/bl/customgrid/widget/grid/column/filter/product/catego</code>

I've tried changing permissions on the directory, but I think its strange that the last directory is called "catego". Is there some kind of maximum character limit for the directory path? The filename is the same on my server (and empty).

**Comment by lelandsmith** [comment]
The Fix worked for me too. Thanks!!! :)
