### ISSUE TITLE
Edit Icon alignment is off after scrolling the grid horizontally

### ISSUE THREAD

**Issue by cfwilson** [mage-eag/mage-enhanced-admin-grids#148]
There appears to be an issue when horizontally scrolling the grid, the edit icon is appearing over different rows than the one to be edited.

![image](https://cloud.githubusercontent.com/assets/1596304/5723906/c0f0bf48-9b15-11e4-9630-234171bc5273.png)

Happening in Magento 1.9.0.1

Thanks

**Comment by mage-eag** [comment]
Sorry for the really late answer !
From your screenshot it seems that the grid overflow is visible, whereas it should be scrollable by default. Are you using a specific extension / admin theme that could cause this behaviour ?
