### ISSUE TITLE
Customer group column rendering

### ISSUE THREAD

**Issue by Bond323** [mage-eag/mage-enhanced-admin-grids#152]
Hello,

I'm using your enhanced admin grids and it's working great. I also want to display the customer group column at the orders page. This is working, but it only shows the ID of the customer group (a number), and not the name of the customer group. How can i make this happen? because i tried all the rendering options and none of them displays the name of the customer group.

Thanks and hope to hear from you guys!

**Comment by mage-eag** [comment]
Sorry for the really late answer !
Assuming you're using the dedicated custom column, you can get the rendering you want by clicking on the cog icon next to _sales_order/customer_group_, then choosing _Yes_ for _Use Default Behaviour_, applying and saving the grid.
