### ISSUE TITLE
Searching in the promotions tab no longer works

### ISSUE THREAD

**Issue by dannyxm43** [mage-eag/mage-enhanced-admin-grids#153]
Hi There,

We are currently running Magento Enterprise 1.13.1.0 installed your extension onto are devolpment site an learned that when we try to search for the coupon codes the search no longer works but this seems to have been addressed in version 1.0.0 of your extension I was wondering if you could point me in the right direction of fixing this issue on your 0.9.0 version of your extension.

Thanks
Dan

**Comment by mage-eag** [comment]
Sorry for the really late answer !
Not sure if this has been specifically fixed (the extension is not officially EE compatible, and I didn't know about this problem), what kind of error do you get when trying to filter the price rules grid ?
