### ISSUE TITLE
Don't save product added to a category from category edit interface.

### ISSUE THREAD

**Issue by simbus82** [mage-eag/mage-enhanced-admin-grids#163]
If i have eag 1.0.0 is enabled, when i go to edit a category, and i check products in the product assignement tab, eag don't save the product assignement to the category. If i disable eag in this view, all is ok.

Thanks.

PS: magento 1.9.0.x and 1.9.1.x

**Comment by domj85** [comment]
I have the same problem but i have resolved this issue enabling the position column.
When you enable this column the grid will work properly.

**Comment by simbus82** [comment]
Thanks @domj85! How i can enable position column?

**Comment by mage-eag** [comment]
@simbus82 
Sorry for the late answer !
Can you paste here a screenshot of the columns list from the category products grid ? (as @domj85 mentioned, the position column is required in order for Magento to save the assignations)
