### ISSUE TITLE
Invalid method /BL/CustomGrid/Block/Widget/Grid/Editor/Form/Helper/Product/Wysiwyg.php(26)

### ISSUE THREAD

**Issue by JosVerhaar** [mage-eag/mage-enhanced-admin-grids#164]
We receive this error when trying to change the description via the grid of a product.

Invalid method BL_CustomGrid_Block_Widget_Grid_Editor_Form_Helper_Product_Wysiwyg::helper(Array
(
    [0] => adminhtml
)
)

Trace:
#0 /var/www/vhosts/URL/httpdocs/.modman/BL_CustomGrid/app/code/community/BL/CustomGrid/Block/Widget/Grid/Editor/Form/Helper/Product/Wysiwyg.php(26): Varien_Object->__call('helper', Array)
#1 /var/www/vhosts/URL/httpdocs/.modman/BL_CustomGrid/app/code/community/BL/CustomGrid/Block/Widget/Grid/Editor/Form/Helper/Product/Wysiwyg.php(26): BL_CustomGrid_Block_Widget_Grid_Editor_Form_Helper_Product_Wysiwyg->helper('adminhtml')
#2 /var/www/vhosts/URL/httpdocs/lib/Varien/Data/Form/Element/Textarea.php(56): BL_CustomGrid_Block_Widget_Grid_Editor_Form_Helper_Product_Wysiwyg->getAfterElementHtml()
#3 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Adminhtml/Block/Catalog/Form/Renderer/Fieldset/Element.php(189): Varien_Data_Form_Element_Textarea->getElementHtml()
#4 /var/www/vhosts/URL/httpdocs/.modman/BL_CustomGrid/app/design/adminhtml/default/default/template/bl/customgrid/widget/grid/editor/form/renderer/product/fieldset/element.phtml(57): Mage_Adminhtml_Block_Catalog_Form_Renderer_Fieldset_Element->getElementHtml()
#5 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Block/Template.php(241): include('/var/www/vhosts...')
#6 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#7 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#8 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#9 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#10 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Adminhtml/Block/Widget/Form/Renderer/Fieldset/Element.php(52): Mage_Core_Block_Abstract->toHtml()
#11 /var/www/vhosts/URL/httpdocs/lib/Varien/Data/Form/Element/Abstract.php(223): Mage_Adminhtml_Block_Widget_Form_Renderer_Fieldset_Element->render(Object(BL_CustomGrid_Block_Widget_Grid_Editor_Form_Helper_Product_Wysiwyg))
#12 /var/www/vhosts/URL/httpdocs/lib/Varien/Data/Form/Element/Abstract.php(233): Varien_Data_Form_Element_Abstract->getHtml()
#13 /var/www/vhosts/URL/httpdocs/lib/Varien/Data/Form/Element/Fieldset.php(90): Varien_Data_Form_Element_Abstract->toHtml()
#14 /var/www/vhosts/URL/httpdocs/.modman/BL_CustomGrid/app/design/adminhtml/default/default/template/bl/customgrid/widget/grid/editor/form/renderer/fieldset.phtml(67): Varien_Data_Form_Element_Fieldset->getChildrenHtml()
#15 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Block/Template.php(241): include('/var/www/vhosts...')
#16 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#17 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#18 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#19 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#20 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Adminhtml/Block/Widget/Form/Renderer/Fieldset.php(51): Mage_Core_Block_Abstract->toHtml()
#21 /var/www/vhosts/URL/httpdocs/lib/Varien/Data/Form/Element/Abstract.php(223): Mage_Adminhtml_Block_Widget_Form_Renderer_Fieldset->render(Object(Varien_Data_Form_Element_Fieldset))
#22 /var/www/vhosts/URL/httpdocs/lib/Varien/Data/Form/Element/Abstract.php(233): Varien_Data_Form_Element_Abstract->getHtml()
#23 /var/www/vhosts/URL/httpdocs/lib/Varien/Data/Form.php(244): Varien_Data_Form_Element_Abstract->toHtml()
#24 /var/www/vhosts/URL/httpdocs/lib/Varien/Data/Form.php(256): Varien_Data_Form->toHtml()
#25 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Adminhtml/Block/Widget/Form.php(108): Varien_Data_Form->getHtml()
#26 /var/www/vhosts/URL/httpdocs/.modman/BL_CustomGrid/app/design/adminhtml/default/default/template/bl/customgrid/widget/grid/editor/form.phtml(19): Mage_Adminhtml_Block_Widget_Form->getFormHtml()
#27 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Block/Template.php(241): include('/var/www/vhosts...')
#28 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#29 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#30 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#31 /var/www/vhosts/URL/httpdocs/.modman/BL_CustomGrid/app/code/community/BL/CustomGrid/Block/Widget/Grid/Editor/Form/Abstract.php(67): Mage_Adminhtml_Block_Template->_toHtml()
#32 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Block/Abstract.php(919): BL_CustomGrid_Block_Widget_Grid_Editor_Form_Abstract->_toHtml()
#33 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#34 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('form', true)
#35 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Adminhtml/Block/Widget/Form/Container.php(130): Mage_Core_Block_Abstract->getChildHtml('form')
#36 /var/www/vhosts/URL/httpdocs/.modman/BL_CustomGrid/app/code/community/BL/CustomGrid/Block/Widget/Grid/Editor/Form/Container.php(49): Mage_Adminhtml_Block_Widget_Form_Container->getFormHtml()
#37 /var/www/vhosts/URL/httpdocs/.modman/BL_CustomGrid/app/design/adminhtml/default/default/template/bl/customgrid/widget/grid/editor/form/container.phtml(38): BL_CustomGrid_Block_Widget_Grid_Editor_Form_Container->getFormHtml()
#38 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Block/Template.php(241): include('/var/www/vhosts...')
#39 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#40 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#41 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#42 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Adminhtml/Block/Widget/Container.php(308): Mage_Adminhtml_Block_Template->_toHtml()
#43 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Widget_Container->_toHtml()
#44 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#45 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Text_List->_toHtml()
#46 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#47 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#48 /var/www/vhosts/URL/httpdocs/app/design/adminhtml/default/default/template/popup.phtml(63): Mage_Core_Block_Abstract->getChildHtml('content')
#49 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Block/Template.php(241): include('/var/www/vhosts...')
#50 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#51 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#52 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#53 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#54 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#55 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#56 /var/www/vhosts/URL/httpdocs/.modman/BL_CustomGrid/app/code/community/BL/CustomGrid/controllers/Grid/EditorController.php(91): Mage_Core_Controller_Varien_Action->renderLayout()
#57 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(418): BL_CustomGrid_Grid_EditorController->editAction()
#58 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#59 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#60 /var/www/vhosts/URL/httpdocs/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#61 /var/www/vhosts/URL/httpdocs/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#62 /var/www/vhosts/URL/httpdocs/index.php(87): Mage::run('', 'store')
#63 {main}

**Comment by mage-eag** [comment]
Fixed in 6afd05aeed56a01f5a3070d848fa68e05b5458a8, thanks !
