### ISSUE TITLE
Conflict with another extension

### ISSUE THREAD

**Issue by bogratt** [mage-eag/mage-enhanced-admin-grids#178]
Hi - I am not great with Magento but I have a conflict with AITOC multi-location inventory module. They say it needs to be fixed on the enhanced admin grids module - it breaks the view products page. The log is below. If I disable the EPG is works. Any help? Thanks in advance!

a:5:{i:0;s:94:"Item (Aitoc_Aitpermissions_Model_Rewrite_CatalogProduct) with the same id "1020" already exist";i:1;s:5730:"#0 /usr/www/users/xxxxx/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(265): Varien_Data_Collection->addItem(Object(Aitoc_Aitpermissions_Model_Rewrite_CatalogProduct))
#1 /usr/www/users/xxxxx/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(1055): Mage_Eav_Model_Entity_Collection_Abstract->addItem(Object(Aitoc_Aitpermissions_Model_Rewrite_CatalogProduct))
#2 /usr/www/users/xxxxx/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(871): Mage_Eav_Model_Entity_Collection_Abstract->_loadEntities(false, false)
#3 /usr/www/users/xxxxx/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(533): Mage_Eav_Model_Entity_Collection_Abstract->load()
#4 /usr/www/users/xxxxx/var/ait_rewrite/Mage_Adminhtml_Block_Catalog_Product_Grid.php(427): Mage_Adminhtml_Block_Widget_Grid->_prepareCollection()
#5 /usr/www/users/xxxxx/app/code/community/BL/CustomGrid/Model/Grid/Rewriter/Eval.php(32) : eval()'d code(96): Inchoo_Productfilter_Block_Grid->_prepareCollection()
#6 /usr/www/users/xxxxx/app/code/community/BL/CustomGrid/Model/Grid/Rewriter/Eval.php(32) : eval()'d code(382): BL_CustomGrid_Block_Rewrite_Inchoo_Productfilter_Block_Grid->_prepareCollection()
#7 /usr/www/users/xxxxx/app/code/community/BL/CustomGrid/Model/Observer.php(562): BL_CustomGrid_Block_Rewrite_Inchoo_Productfilter_Block_Grid->blcg_finishPrepareCollection()
#8 /usr/www/users/xxxxx/app/code/community/BL/CustomGrid/Model/Grid/Rewriter/Eval.php(32) : eval()'d code(93): BL_CustomGrid_Model_Observer->afterGridPrepareCollection(Object(BL_CustomGrid_Block_Rewrite_Inchoo_Productfilter_Block_Grid))
#9 /usr/www/users/xxxxx/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(626): BL_CustomGrid_Block_Rewrite_Inchoo_Productfilter_Block_Grid->_prepareCollection()
#10 /usr/www/users/xxxxx/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(632): Mage_Adminhtml_Block_Widget_Grid->_prepareGrid()
#11 /usr/www/users/xxxxx/app/code/core/Mage/Core/Block/Abstract.php(918): Mage_Adminhtml_Block_Widget_Grid->_beforeToHtml()
#12 /usr/www/users/xxxxx/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#13 /usr/www/users/xxxxx/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('grid', true)
#14 /usr/www/users/xxxxx/app/code/core/Mage/Adminhtml/Block/Catalog/Product.php(79): Mage_Core_Block_Abstract->getChildHtml('grid')
#15 /usr/www/users/xxxxx/app/design/adminhtml/default/default/template/catalog/product.phtml(46): Mage_Adminhtml_Block_Catalog_Product->getGridHtml()
#16 /usr/www/users/xxxxx/app/code/core/Mage/Core/Block/Template.php(241): include('/usr/www/users/...')
#17 /usr/www/users/xxxxx/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#18 /usr/www/users/xxxxx/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#19 /usr/www/users/xxxxx/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#20 /usr/www/users/xxxxx/app/code/core/Mage/Adminhtml/Block/Widget/Container.php(308): Mage_Adminhtml_Block_Template->_toHtml()
#21 /usr/www/users/xxxxx/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Widget_Container->_toHtml()
#22 /usr/www/users/xxxxx/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#23 /usr/www/users/xxxxx/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Text_List->_toHtml()
#24 /usr/www/users/xxxxx/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#25 /usr/www/users/xxxxx/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#26 /usr/www/users/xxxxx/app/design/adminhtml/default/default/template/page.phtml(74): Mage_Core_Block_Abstract->getChildHtml('content')
#27 /usr/www/users/xxxxx/app/code/core/Mage/Core/Block/Template.php(241): include('/usr/www/users/...')
#28 /usr/www/users/xxxxx/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#29 /usr/www/users/xxxxx/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#30 /usr/www/users/xxxxx/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#31 /usr/www/users/xxxxx/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#32 /usr/www/users/xxxxx/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#33 /usr/www/users/xxxxx/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#34 /usr/www/users/xxxxx/app/code/core/Mage/Adminhtml/controllers/Catalog/ProductController.php(180): Mage_Core_Controller_Varien_Action->renderLayout()
#35 /usr/www/users/xxxxx/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_Catalog_ProductController->indexAction()
#36 /usr/www/users/xxxxx/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('index')
#37 /usr/www/users/xxxxx/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#38 /usr/www/users/xxxxx/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#39 /usr/www/users/xxxxx/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#40 /usr/www/users/xxxxx/index.php(87): Mage::run('', 'store')
#41 {main}";s:3:"url";s:82:"/index.php/admin/admin/catalog_product/index/key/xxxxxxxxxxxxxxxxxxxxxxxxxx/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}

**Comment by bogratt** [comment]
Hi - I actually got this working - what would be nice is if this could be compatible with the multi-store inventory so that if you edit an inventory number in a store view it would change that inventory number and not the default. Would be awesome. Thx!

**Comment by mage-eag** [comment]
Sorry to give you the same answer as AITOC, but this feature should rather be implemented on their end (it is too much specific, further being related to a commercial extension, so it could not become a priority before at least a long time)

**Comment by hyperbbing** [comment]
@bogratt Hi, I have the same problem. Would you mind to share how were you able to fix this?

**Comment by bogratt** [comment]
@hyperbbing I can't remember exactly but I think what the issue was is displaying one of the inventory attributes in the columns. What I needed to do was do into the EAD list option, and disable something relating to the inventory attributes so that it is not displayed in a column in the manage products page. I remember disabling one by one til I found the one with the issue, then removing that column

**Comment by bogratt** [comment]
@hyperbbing Not sure if you fixed it - but was thinking about it and I think it was the stock availability column/attribute causing my issue. The showing in/out of stock in products list page
