### ISSUE TITLE
SQLSTATE error when sorting the grid on custom column

### ISSUE THREAD

**Issue by nkrosenbrink** [mage-eag/mage-enhanced-admin-grids#179]
Problem:
I filter the orders based on a date selection then sort them based on the payment method and I get an sqlstate error that magento is unable to recover from. 

I have to logout and log back in to make the grid accessible again.

The error message states:

>There has been an error processing your request
>SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'blcg_custom_field_2' in order clause is ambiguous

Please help.

**Comment by mage-eag** [comment]
Seems like two custom columns were given the same ID, what should not happen. Can you check in the source code of the orders grid page if you can find `name="_blcg_custom_column_2"` more than once, and what are the corresponding columns (their headers should be located on the same line) ?
