### ISSUE TITLE
Custom Columns

### ISSUE THREAD

**Issue by digiscape** [mage-eag/mage-enhanced-admin-grids#2]
Using Magento 1.7.0.2 I wanted to add a custom column,
Choosing from any of the custom columns provided shows the following error

Parse error: syntax error, unexpected T_ENCAPSED_AND_WHITESPACE, expecting ')' in /home/jason/public_html/magento/app/code/community/BL/CustomGrid/Helper/Collection.php(100) : runtime-created function on line 1

Fatal error: Function name must be a string in /home/jason/public_html/magento/app/code/community/BL/CustomGrid/Model/Custom/Column/Simple/Table.php on line 75

**Comment by Jeeva-Rathinam** [comment]
what is mean SQLSTATE[42S02]: Base table or view not found: 1146
