### ISSUE TITLE
SUPEE-6285 patch affects access to most controllers

### ISSUE THREAD

**Issue by mwgamble** [mage-eag/mage-enhanced-admin-grids#203]
The recent security patch from Magento changes the default check to see if an admin user can use a particular controller. Unless a controller specifically overrides the ``_isAllowed()`` method with its own check, the default is now that the user must have permission to use everything, otherwise their access will be denied.

Unfortunately, it appears that most controllers in this extension do not override the ``_isAllowed()`` check, and as such prevent users with limited privileges from using most features of the extension. Do you have a timeline for when this will be remedied? Additionally, is there any way we can support this process?

**Comment by mage-eag** [comment]
Thanks for the recall !

The fixes have been commited on the different branches :
- 1.0.0-wip : 8bc41ea66bf31e597107639076f24d33ee79ad19
- 0.9.0 : bc397ab5a4b808db71313ab404a924168b41b1c2
- 0.8.9 : 3ebf84c14686cf3756d347f9f3b6a63ea9d3b33a

And I will try to release the 0.9.0 version (including the fix) on the Magento Connect asap.

**Comment by mage-eag** [comment]
The 0.9.0 version is now available on the Magento Connect
