### ISSUE TITLE
Edit Shipping Method Name/Style

### ISSUE THREAD

**Issue by adam105** [mage-eag/mage-enhanced-admin-grids#204]
Hi,

I saw this issue but it didn't seem to address the following question: https://github.com/mage-eag/mage-enhanced-admin-grids/issues/135

I added a custom "Shipping Method" column. How can I change the shipping method value that is currently displayed? Instead of "matrixrate_matrixrate_10", I would like it to say "Express Mail" and instead of "matrixrate_matrixrate_free" it should say "Regular post". If it's something that needs to be custom coded, which file(s) would I look in?

Also, how would I change the color of those values to something different?

Looks like a great extension, really happy you made it - thank you!

**Comment by mwgamble** [comment]
You need to define what's called an options source. Go to System > Custom Grids > Manage Options Source in the admin panel, then click the Add button in the top-right corner of the page.

Here, you want to define a source of type "Magento Model". Give it a name, then switch over to the second tab. The important settings are as below:

- name: `customgrid/system_config_source_shipping_methods`
- method: `toOptionArray`
- return type: Options Array
- value key: `value`
- label key: `label`

Save that, then go back to the grid editor for the grid you're working on. In the rendering column, there should be a dropdown for your field. Select "options" in this dropdown, then click on the gear icon. In the popup that appears, there should be a setting right near the top named "Options Source". Pick the source you just created, then save everything, and it should behave exactly as you expect :).

To the developer: I feel like some of the more common source models, such as yesno, payment methods and shipping methods, should be created by default when first installing the extension. What do you think?

**Comment by sabonmichal** [comment]
thanks! I went through the steps but it didn't seem to work. A screencast illustrating the process would be super helpful. Yes, creating those more common source models by default would be useful.

**Comment by mage-eag** [comment]
@sabonmichal 
Which version of the extension do you use ? As @mwgamble stated, you need to create an options source, but the `customgrid/system_config_source_shipping_methods` model only exists in the 1.0.0-wip version. Another possibility can be to create an options source with the _Custom List_ type, which allows you to define your own mapping.

@mwgamble 
Thanks for your answers to some of the issues ! :)
Regarding the common options sources, that's a good idea, marking this issue as an enhancement to keep track of it.

**Comment by sabonmichal** [comment]
ok, I didn't realize - we are using version 0.9.0. Great extension, thanks for putting this out there and looking forward to trying version 1.0.0 once it's stable!!

**Comment by adam105** [comment]
ok, I didn't realize - we are using version 0.9.0. Great extension, thanks for putting this out there and looking forward to trying version 1.0.0 once it's stable!!
