### ISSUE TITLE
Use Price/Description Column Edit Renderer for Custom Grid

### ISSUE THREAD

**Issue by sprankhub** [mage-eag/mage-enhanced-admin-grids#207]
I would like to use the price and the description column edit renderer in a custom grid.

More specific, I have a custom grid with a price column, which should be editable. The price is currently editable with a simple text field, which is nice. But I would like to have the same edit functionality as in the `adminhtml/catalog_product_grid` grid. I also want to have this kind of view:
![image](https://cloud.githubusercontent.com/assets/930199/8830828/b8ca745c-309e-11e5-86b9-3987ebd86f65.png)

How can I achieve that? I would like to achieve the same with the description field.

I tried it with different values for the `edit_block_type` in my `BL_CustomGrid_Model_Grid_Type_Abstract#_getBaseEditableFields`, but could not make it.

Thanks in advance!

**Comment by mwgamble** [comment]
You need to look at the following methods, all in the class you mentioned:

- `_getEntityRowIdentifiersKeys`
- `_loadEditedEntity`
- `_getEditRequiredAclPermissions`

**Comment by sprankhub** [comment]
@mwgamble this only helps for adding editing functionality to a custom grid. I also have that. But this does not help to have the price/description renderer, which have special functionality like the currency display...

**Comment by mage-eag** [comment]
Sorry for the late answer !

Actually, all of the editors fields use more or less the same renderers as their base Magento counterpart. Eg, product price fields are handled by [BL_CustomGrid_Block_Widget_Grid_Editor_Form_Helper_Product_Price](https://github.com/mage-eag/mage-enhanced-admin-grids/blob/1.0.0-wip/app/code/community/BL/CustomGrid/Block/Widget/Grid/Editor/Form/Helper/Product/Price.php), which inherits from [Mage_Adminhtml_Block_Catalog_Product_Helper_Form_Price](https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Adminhtml/Block/Catalog/Product/Helper/Form/Price.php).

One side note regarding the editors and version 1.0.0, I'm currently working on refactoring this part of the code. For existing editors, this will mosty imply values and methods rearrangement  - I'll try to write a FAQ section about how to port old code to the new code base.
Afterwards, things should be more meaningful and extensible, and all the clutter will happily be gone from [BL_CustomGrid_Model_Grid_Type_Abstract](https://github.com/mage-eag/mage-enhanced-admin-grids/blob/0.9.0/app/code/community/BL/CustomGrid/Model/Grid/Type/Abstract.php) :)

**Comment by sprankhub** [comment]
Thanks for the answer. But my question is still not really answered... How can I define that in a custom grid, a column should be handled by `BL_CustomGrid_Block_Widget_Grid_Editor_Form_Helper_Product_Price`, so that the edit field is rendered like a real price field? Thanks!

**Comment by mage-eag** [comment]
You will need to write your own block class inspired from `BL_CustomGrid_Block_Widget_Grid_Editor_Form_Helper_Product_Price`, because the latter requires a price attribute to work (if you already know how to get the store and tax class on which your prices will be based, then this should be fairly easy).
Once your block will be ready, you should be able to use it by setting its class code in `edit_block_type` :)

**Comment by sprankhub** [comment]
Ahh thanks a lot :)
