### ISSUE TITLE
Add Release Tag

### ISSUE THREAD

**Issue by jhoelzl** [mage-eag/mage-enhanced-admin-grids#218]
Please add git tag version number 0.9.0 under https://github.com/mage-eag/mage-enhanced-admin-grids/releases for a proper composer useage. Thanks!

**Comment by mage-eag** [comment]
The tag has been created : https://github.com/mage-eag/mage-enhanced-admin-grids/releases/tag/0.9.0, thanks for the suggestion :)

**Comment by jhoelzl** [comment]
Thanks!
