### ISSUE TITLE
Exported selection does not match filters

### ISSUE THREAD

**Issue by ajpevers** [mage-eag/mage-enhanced-admin-grids#242]
When I export a filtered creditmemo collection for instance with the filter increment_id=100002241 the CSV export gives me item 100002242.

All Credit Memo's
![screen shot 2015-10-27 at 13 37 30](https://cloud.githubusercontent.com/assets/1489129/10758199/1813e990-7cb0-11e5-9774-fa329e3f469f.png)

Filtered Selection:
![screen shot 2015-10-27 at 13 37 46](https://cloud.githubusercontent.com/assets/1489129/10758200/19f227e0-7cb0-11e5-92b2-1ca98d31bca2.png)

Export:
![screen shot 2015-10-27 at 13 38 04](https://cloud.githubusercontent.com/assets/1489129/10758202/1c39f352-7cb0-11e5-96d5-5772ff6a518a.png)

Result:
```
"Credit Memo # ","Created At","Order # ","Order Date","Bill to Name",Status,Refunded,"Total excl. Tax","Tax 21%","Tax 6%","Tax 18%","Tax Amount"
100002242,"Oct 27, 2015 9:15:40 AM",100027644,"Oct 27, 2015 9:05:40 AM","Anton Evers",Refunded,45.9,37.93,1.9000,0.0000,6.0700,7.9700
```

The query performed is:
```
SELECT `main_table`.*, (`main_table`.`grand_total` - `main_table`.`tax_amount`) AS `total_excl_tax`, Coalesce(Sum(oi21.tax_invoiced), 0) AS tax21, Coalesce(Sum(oi6.tax_invoiced), 0) AS tax6, Coalesce(Sum(oi18.tax_invoiced), 0) AS tax18 FROM `sales_flat_creditmemo_grid` AS `main_table`
 LEFT JOIN `sales_flat_creditmemo_item` AS `ci` ON main_table.entity_id=ci.parent_id
 LEFT JOIN `sales_flat_order_item` AS `oi21` ON ci.order_item_id=oi21.item_id AND oi21.tax_percent=21
 LEFT JOIN `sales_flat_order_item` AS `oi6` ON ci.order_item_id=oi6.item_id AND oi6.tax_percent=6
 LEFT JOIN `sales_flat_order_item` AS `oi18` ON ci.order_item_id=oi18.item_id AND oi18.tax_percent=18 GROUP BY `main_table`.`entity_id` ORDER BY created_at DESC LIMIT 1
```

As you can see there are some custom joins and a group by, but apart from that the applied filter is nowhere to be seen.

Can you reproduce this?

**Comment by ajpevers** [comment]
@mage-eag Please let me no when you get to this.

**Comment by joost-florijn-kega** [comment]
+1
