### ISSUE TITLE
Not compatible with Magento 1.9.2.2

### ISSUE THREAD

**Issue by rossmc** [mage-eag/mage-enhanced-admin-grids#243]
I just upgraded to Magento 1.9.2.2 and I can no longer edit the grid inline.
![image](https://cloud.githubusercontent.com/assets/2452991/10797213/7d3ffdec-7d99-11e5-8be5-a79ac1798d34.png)

This seems to be due to the supee-6788 security patche that came with this update and it effects admin routing for some extensions.

>BACKWARD COMPATIBILITY
>This patch breaks backward compatibility in ways that can affect your extensions or customizations 
>(see [notes](http://magento.com/security/patches/supee-6788-technical-details)for details). For example, certain updates to admin routing can make improperly coded >extensions and customizations inaccessible from the admin panel. We expect that many extensions >and customizations will be affected by this change, so we are releasing the patch with it included, but >turned off. This lets you immediately benefit from the rest of the patch, while also giving you time to >update your code before turning on the admin routing change.

When I enable *Admin routing compatibility mode for extensions* from the magento backend it works again but this is bad for security.

**Comment by mage-eag** [comment]
Version 0.9.0.1 was specifically released on the 10/23/2015 to address compatibility issues with the latest security patch, can you update your version and tell if that solves your problem ?

**Comment by simkea** [comment]
Branch 1.0.0-wip is correct running under Magento CE 1.9.2.2
br

**Comment by rossmc** [comment]
Version 0.9.0.1 worked, thanks a mil. Brilliant module :)

**Comment by koopjesboom** [comment]
Best,

 

All problems solved, working like a charm!

 

Best regards Bram Koopjesboom V.O.F.

 

Van: Benoît [mailto:notifications@github.com] 
Verzonden: donderdag 29 oktober 2015 10:33
Aan: mage-eag/mage-enhanced-admin-grids
Onderwerp: Re: [mage-enhanced-admin-grids] Not compatible with Magento 1.9.2.2 (#243)

 

Version 0.9.0.1 was specifically released on the 10/23/2015 to address compatibility issues with the latest security patch, can you update your version and tell if that solves your problem ?
