### ISSUE TITLE
Order View - Colors Quit Displaying After Moving Admin to Custom Directory

### ISSUE THREAD

**Issue by llamma123** [mage-eag/mage-enhanced-admin-grids#252]
We loved having the custom colors on admin view of orders screen but one day we decided to move the admin directory to a custom location for better security.   website.com/admin became website.com/somethingcustom and now colors quit displaying on orders screen, furthermore we can try to add the colors back in and they do not appear.  Is there something we need to set?

**Comment by Drifti** [comment]
How did you resolve the problem?

**Comment by llamma123** [comment]
Unfortunately it is still unresolved.  Are you seeing a similar issue?  Did it present itself after moving the admin folder to a new location or as a result of some other activity?

**Comment by llamma123** [comment]
I just looked at it again today and set some colors and they are working again!  We didn't do anything to fix it but after 10 months without colors set we have them again now!
