### ISSUE TITLE
Magento connect error on install

### ISSUE THREAD

**Issue by urwild** [mage-eag/mage-enhanced-admin-grids#261]
http://connect20.magentocommerce.com/community/BL_CustomGrid
Then install
Then error

Checking dependencies of packages
Starting to download BL_CustomGrid-0.9.0.1-beta.tgz ...

CONNECT ERROR: Package not found: BL_CustomGrid 0.9.0.1-beta

**Comment by mage-eag** [comment]
Please see issue #256
