### ISSUE TITLE
still having issues with https://www.magentocommerce.com/magento-connect/enhanced-admin-grids-editor.html

### ISSUE THREAD

**Issue by urwild** [mage-eag/mage-enhanced-admin-grids#263]
Checking dependencies of packages

CONNECT ERROR: Package community/BL_CustomGrid 0.9.2: requires PHP version >= 5.2.0 and <= 5.3.0 current is: 5.5.30

**Comment by mage-eag** [comment]
The dependency on obsolete PHP versions has now been removed from the Magento Connect package, can you try again ?

**Comment by urwild** [comment]
Looks like it is working now.
Thanks

**Comment by mage-eag** [comment]
Glad to hear that, and thanks for having pointed out this problem :)
