### ISSUE TITLE
Group Price?

### ISSUE THREAD

**Issue by rmvdev** [mage-eag/mage-enhanced-admin-grids#292]
Hey there, apologies if this seems like a stupid question but can anyone point me in the direction of adding a group price column to the manage products grid?

I've attempted to simple add it as an attribute but it doesn't work

Regards

**Comment by jehzlau** [comment]
Same problem here. I hope they will add this one in the next update. :D

**Comment by rmvdev** [comment]
Solved this by adding multiple renders with group prices
