### ISSUE TITLE
Adding products through 'category products'

### ISSUE THREAD

**Issue by GladiatorSA** [mage-eag/mage-enhanced-admin-grids#305]
I'm trying to add multiple products to a category using the 'category products' tab.

Hitting the check mark infront of products and saving the category does not save the products to that category.
Removing the checkmark however does remove them from the category.

Could someone help me fix this?
Thank you.

**Comment by nobodyfamouz** [comment]
I have the same issue. As far as I was able to debug it the category_products variable send to the controller is always empty. Anyone with fix?

**Comment by nobodyfamouz** [comment]
I have found the problem. If you hide the column position then no product can be added. Once you make it visible again the products can be added.

Details: javascript code in `app/design/adminhtml/default/default/template/catalog/category/edit/form.phtml`  requires this field position

<pre>
    function registerCategoryProduct(grid, element, checked){
        if(checked){
            if(element.positionElement){ <----
                element.positionElement.disabled = false;
                categoryProducts.set(element.value, element.positionElement.value);
            }
        }
        else{
            if(element.positionElement){
                element.positionElement.disabled = true;
            }
            categoryProducts.unset(element.value);
        }
        $('in_category_products').value = categoryProducts.toQueryString();
        grid.reloadParams = {'selected_products[]':categoryProducts.keys()};
    }
</pre>

**Comment by GladiatorSA** [comment]
Dude, awesome. we have a winner.
I can confirm the fix.

The position column was disable, re-enabling it allows me to save products to the categories again.

Now, it's not a problem to leave the position column enabled, but wouldn't it be better to have a patch to fix this?
So you can add products with the position column disabled.
Or would this break other things?
