### ISSUE TITLE
Custom field error

### ISSUE THREAD

**Issue by craigvc** [mage-eag/mage-enhanced-admin-grids#361]
I added a custom field to the orders page, now when i run a search it jumps to the dashboard and then if i try to get back to the orders page i get an error 
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'main_table.blcg_custom_field_5' in 'where clause', query was: SELECT COUNT(*) FROM `mage_sales_flat_order_grid` AS `main_table` WHERE (`main_table`.`blcg_custom_field_5` LIKE '%cool%')

**Comment by devzorg** [comment]
Was fixed by this guy
https://www.garybell.co.uk/fix-magento-invalid-attribute-error-supee-11219/
awesome
