### ISSUE TITLE
Security vulnerability, don't use this extension

### ISSUE THREAD

**Issue by gwillem** [mage-eag/mage-enhanced-admin-grids#364]
See https://gwillem.gitlab.io/2018/10/23/magecart-extension-0days/

**Comment by ThomasNegeli** [comment]
@gwillem 
Are you sure that the lastest version of the extension is really affected?
The admin path 

> customgrid

does not exist in the latest version.
Additionally, this extension is backend only. So the hacker needs access to a valid backend account, to do bad things.

But, you are right with the fact, that this extension massively uses serialize and unserialize functionality.

**Comment by gwillem** [comment]
Whoops, I didn't go very deep there, only checked for unserialize existence. The attacker did send a customized payload for this route, which made me jump to conclusions.
