### ISSUE TITLE
Does a M2 version exist? Or an Extension that does the same?

### ISSUE THREAD

**Issue by seansan** [mage-eag/mage-enhanced-admin-grids#368]
Does a M2 version exist? Or an Extension that does the same?

Much obliged

In M2 I understand we can add columns per default?

But in M2 we cannot create TABS, where the columns, sorting and order of columns is stored. And more importantly the filtering of the collection. So when I click TAB A  I see my product set column design for a certain stored filter, For TAB B different columns and a different filter etc

![image](https://user-images.githubusercontent.com/652395/55332087-f42d1900-5494-11e9-9d7d-c32c01c76994.png)

**Comment by hamzarhd** [comment]
does anyone find something on this?

**Comment by seansan** [comment]
M2 has saved filters by default

and I advise Mirasvit ADMIN LABELS extension where you can save all
grids/filters/columns

https://mirasvit.com/magento-2-admin-bookmarks.html

**Comment by hamzarhd** [comment]
thanks a lot

**Comment by seansan** [comment]
plz close
