### ISSUE TITLE
Customer Group custom column failing on scope-limited accounts

### ISSUE THREAD

**Issue by Morgon** [mage-eag/mage-enhanced-admin-grids#65]
Hello - We're having trouble on Enterprise with scope-limited accounts (admin accounts who have access only to one website, rather than a normal 'global' admin with access to any store) and a custom column of Customer Group. 

The original exception was that 'store_id' is ambiguous. I was able to get the query generating the exception, and it's easy to see why it's failing:

```
SELECT `main_table`.*, 
  `_blcgmccocg_e229fbaa727cc57d1f68c0402db32809`.`customer_group_id`
  AS `blcg_custom_field_1`
FROM `sales_flat_order_grid` AS `main_table`
LEFT JOIN `sales_flat_order` AS `_blcgmccocg_e229fbaa727cc57d1f68c0402db32809`
  ON `_blcgmccocg_e229fbaa727cc57d1f68c0402db32809`.`entity_id` = `main_table`.`entity_id`
WHERE (store_id IN('3'))
ORDER BY created_at DESC
LIMIT 20
```

Oddly, as a global admin explicitly filtering by a particular store, it works just fine.
It's just odd that this store_id isn't being qualified with a prefix (i.e. `main_table`), since most of your code explicitly does. Not sure where/how to continue debugging the source of this.

I know I mentioned this is Enterprise, however the stack trace is not calling any Enterprise code. I don't know if it will be helpful, but here's a reverse trace, starting (at the bottom) from when the Custom Grid code starts coming into play, until the exception is called:

```
0 MAGENTO/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
1 MAGENTO/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
2 MAGENTO/lib/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array)
3 MAGENTO/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `main_ta...', Array)
4 MAGENTO/lib/Varien/Db/Adapter/Pdo/Mysql.php(428): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `main_ta...', Array)
5 MAGENTO/lib/Zend/Db/Adapter/Abstract.php(734): Varien_Db_Adapter_Pdo_Mysql->query('SELECT `main_ta...', Array)
6 MAGENTO/lib/Varien/Data/Collection/Db.php(734): Zend_Db_Adapter_Abstract->fetchAll('SELECT `main_ta...', Array)
7 MAGENTO/app/code/core/Mage/Core/Model/Resource/Db/Collection/Abstract.php(521): Varien_Data_Collection_Db->_fetchAll('SELECT `main_ta...', Array)
8 MAGENTO/lib/Varien/Data/Collection/Db.php(566): Mage_Core_Model_Resource_Db_Collection_Abstract->getData()
9 MAGENTO/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(533): Varien_Data_Collection_Db->load()
10 MAGENTO/app/code/core/Mage/Adminhtml/Block/Sales/Order/Grid.php(61): Mage_Adminhtml_Block_Widget_Grid->_prepareCollection()
11 MAGENTO/app/code/community/BL/CustomGrid/Model/Observer.php(544) : eval()'d code(97): Mage_Adminhtml_Block_Sales_Order_Grid->_prepareCollection()
12 MAGENTO/app/code/community/BL/CustomGrid/Model/Observer.php(544) : eval()'d code(378): BL_CustomGrid_Block_Rewrite_Sales_Order_Grid->_prepareCollection()
13 MAGENTO/app/code/community/BL/CustomGrid/Model/Observer.php(940): BL_CustomGrid_Block_Rewrite_Sales_Order_Grid->blcg_finishPrepareCollection()
14 MAGENTO/app/code/community/BL/CustomGrid/Model/Observer.php(544) : eval()'d code(94): BL_CustomGrid_Model_Observer->afterGridPrepareCollection(Object(BL_CustomGrid_Block_Rewrite_Sales_Order_Grid))
```

Any thoughts? At least on where I could best try to find/intercept the existing WHERE clause and qualify the store_id parameter? Thank you!

**Comment by seansan** [comment]
Just to confirm we also have this error

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'blcg_custom_field_1' in 'where clause'`

We changed store name colum to only inlclude the storename (1 row). Now when we filter on a certain store the error occurs
