### ISSUE TITLE
Mage registry key "product_collection" already exists

### ISSUE THREAD

**Issue by huynhvothinh** [mage-eag/mage-enhanced-admin-grids#96]
At Manage Product page,  I click 'Sort Columns' and then 'Save Sorting', that error happened, traced: app/code/local/Amasty/Pgrid/Block/Adminhtml/Catalog/Product/Grid.php(125): Mage::register('product_collect...', Object(OrganicInternet_SimpleConfigurableProducts_Catalog_Model_Resource_Eav_Mysql4_Product_Collection))

=> I commented line 125 in Grid.php to make my page continue to run at the momment.
//Mage::register('product_collection', $sortCollection);

**Comment by Wakie87** [comment]
For anyone else with this problem, you most likely don't want to run both the Amasty Product grid and this product together. So what you have to do is the following:

1. Go to "Configuration > Advanced > Advanced" and disable "Amasty_Pgrid"
2. Edit app/etc/modules/Amasty_XXX.xml file (where XXX stands for the extension name/code).
3. Change "true" to "false".
4. Clear the cache.
5. Logout of the admin area and re-login
